---
title: "Untitled"
output: html_document
---

```{r}
library(jsonlite)
library(tidyjson)  
library(dplyr) 
library(stringr) 

dp = readLines("~/le_kutezh/businesses_2.txt")

test = '
http://www.dianping.com/shop/1567174 ^ {"0":"1567174","30":""}
http://www.dianping.com/shop/1567273 ^ {"0":"1567273","30":""}
'
dp_e = stringr::str_c(dp, collapse = "\n")
dp_e = stringr::str_replace_all(dp_e, "http\\:.*\\^ ", "")
dp_e = stringr::str_replace_all(dp_e, "\\}\n\\{", "},{")
dp_e = stringr::str_c("[", dp_e, "]")

dp_p = jsonlite::fromJSON(dp_e)

write.csv(dp_p, "dian_ping.csv" )
```

```{r}
# load filtered data - only rests from beijing and shanghai
dp_bs = read.csv("/students/dvchuprina/le_kutezh/dp_bs.csv")


dp_bs$r <- as.factor(dp_bs$r)
dp_bs$w <- as.factor(dp_bs$w)
no_lat <- filter(dp_bs, r== "1000", w=="1000")

library(ggmap)
colnames(no_lat)<-c("a","name","d","e","f","g","h", "address", "j", "k","l","p","r","w","x")
no_lat$address<- as.vector(no_lat$address)
#addresses = no_lat$address
#addresses = paste0(addresses, ", China")
addr <- geocode(no_lat$address)
addr <- data.frame(cbind(no_lat$name, no_lat$address, addr))
write.csv(addr, "unknown_addresses.csv")
```

```{r}
library(leaflet)
library(readr)
library(dplyr)
```

```{r}
unknown_addresses <- read_csv("/students/dvchuprina/proect_kutezh/unknown_addresses.csv")
```

```{r}
ad = unknown_addresses
ad = na.omit(ad)
ad = filter(ad, no_lat.address != "多家连锁店")

```

```{r}
st_popup <- paste0("<strong>lon: </strong>", 
ad$lon, 
"<br><strong>lat: </strong>", 
ad$lat)

m <- leaflet() %>%
addTiles() %>%
addMarkers(lng=ad$lon, lat=ad$lat, popup = st_popup)

m
```
 
```{r}
unknown_addresses[59, 4] = NA
unknown_addresses[59, 5] = NA
unknown_addresses[274, 4] = NA
unknown_addresses[274, 5] = NA
unknown_addresses[454, 4] = NA
unknown_addresses[454, 5] = NA
unknown_addresses[97, 4] = NA
unknown_addresses[97, 5] = NA
unknown_addresses[588, 4] = NA
unknown_addresses[588, 5] = NA
unknown_addresses[638, 4] = NA
unknown_addresses[638, 5] = NA
unknown_addresses <- unknown_addresses[-c(326), ] 
```



