```{r}
library(readr)
library(tidyr)

library(plyr)
library(dplyr)
library(devtools)
library(RCurl)
source_url("https://gist.githubusercontent.com/Viktor13/3a8b613167091f8a4b66c6e180359186/raw/b340e6fcb9bd8fd80142d867ef4a9e6f5986c2d5/list_recursive_extraction.R")

```

Shanghai
```{r}
shang1 <- RJSONIO::fromJSON("result_shang.json")
shang2 <- RJSONIO::fromJSON("result3_shang.json")
shang2 = shang2[3101:length(shang2)]

lists = ls()
lists = lists[str_detect(lists, "shang")]

# собираем листы из окружения
lists = lapply(lists, get)

# убираем первый элемент с количеством комментов
lists = lapply(1:length(lists), function(x){ lists[[x]][2:length(lists[[x]])] })

# делаем данные одним сплошным листом, а не листом из листов
shang = do.call(c, lists)

shang1 = as.data.frame(shang)

test = list_recursive_extraction(shang[[1]])
test = sapply(shang, function(x){ as.data.frame(t(list_recursive_extraction(x)), stringsAsFactors = F) } )

test_df = do.call(plyr::rbind.fill, test)

View(test_df)
```

```{r}
test_df$query_n = as.numeric(test_df$query_n)
test_df1 = test_df %>% arrange(query_n)
test_df1 = test_df1[1:8964,]

write.csv(test_df1, "shang_trip.csv", row.names = F)
```

```{r}
shang_trip = read.csv("/students/dvchuprina/proect_kutezh/shang_trip.csv")
```

