---
title: "kit_guys"
output: html_document
---

```{r setup, include=FALSE}
rest <- read.csv("~/proect_kutezh/location.csv")
ch_test = read.csv("/students/dvchuprina/proect_kutezh/ch_test.csv")
names(rest) <- c("restId", "city", "tag")
ch_test$restId = as.factor(ch_test$restId)
rest$restId = as.factor(rest$restId)
rest$tag = as.character(rest$tag)
rest <- rest[c(1,3,15)]

ch = left_join(ch_test, rest, by = "restId")
kit_guys <- c (3326812, 5251044, 2638603, 5213409, 4217882, 3658510, 2011903, 1970962, 510194, 2861842, 2233750, 4544369, 4661835, 3681277, 4078867, 2066560, 1953784, 511003, 513052, 2103739, 2795662, 514403, 2859808, 515530, 507942)

beijingren <- c(5, 5, 4, 5, 5, 3, 4, 5, 5, 5, 5, 4, 3, 3, 3, 5, 5, 3, 5, 4, 4, 5, 3, 5, 4)
taiwanwoman <- c(4, 5, 4, 4, 3, 4, 5, 4, 4, 3, 4, 3, 4, 4, 3, 3, 3, 4, 4, 3, 5, 4, 4, 3, 5)
fujianren <- c(4, 4, 5, 4, 4, 3, 4, 4, 4, 3, 3, 3, 5, 5, 3, 3, 4, 5, 4, 5, 4, 4, 4, 3, 5)
georgii <- c(3, 3, 2, 5, 3, 5, 4, 2, 1, 2, 1, 1, 2, 3, 2, 2, 4, 3, 4, 2, 5, 3, 4, 2, 3)
madrussian <- c(3, 2, 5, 3, 5, 3, 4, 2, 3, 4, 2, 1, 3, 5, 4, 5, 3, 2, 3, 4, 3, 5, 3, 5, 4)

kit_guys <- data.frame(Restaurant = kit_guys, Beijing_ren = beijingren, Taiwan_crazy_woman = taiwanwoman, From_Fujian_love_it = fujianren, Georgii_estet = georgii, Mad_russian_Max = madrussian)

write.csv(kit_guys, "kit_guys.csv", row.names = F)
```


1879615 - 川菜	
1893208 - 茶馆
1895356 - 西式甜点
1897006 - 韩国料理
1906186 - 本帮菜 (местная шанхайская кухня)
1902124 - 面包
1936837 - 烧烤 (сухо зажарить; подрумянить (на огне мясо); барбекю; гриль)
1952347 - 麻辣烫 (суп "малатан", острый суп)
2001943 - 火锅 (хого)
2007952 - 馄饨 (вонтоны, хуньтунь, круглые ушки (мелкие пельмени в супе))
2014417 - 粤菜 (кантонская кухня)
2020357 - 湘菜 (хунаньская кухня)
2037652 - 生煎 (обжареные мясные пампушки-баоцзы (традиционное шанхайское блюдо))
2038774 - 意大利菜 
5113390 - 港台甜品 (Гонкогские и Тайваньские сласти)
512206 - 拉美烧烤 (Латинское барбекю)
512899 - 家常菜 (домашняя еда)
505501 - 绍兴菜 (Шаосинская еда)
506436 - 西餐
506818 - 东北菜
507231 - 锅贴 (жареные пельмени)
507910 - 羊蝎子 (тушеный бараний позвоночник)
2130466 - 西北菜
2136673 - 山西菜

1. Пекинец Вася, обожает европейскую еду, преимущественно итальянскую, но при этом уплетает лапшу каждый день в любимой лапшичной - остренькую 
2. Тайванка Маша, тащится по сычуаньскому перцу, ест только пищу с ним, но при этом любит навернуть шаньдунских супчиков, потому что обожает искть новые вкусы в китайской еде
3. Гонконгец Петя в основном ест кантонскую еду, потому что никуда не выезжал в своей жизни после переезда в Гонконг, но иногда ностальгирует по супчику, который готовила его мама в Фуцзяне
4. Георгий из Цзянсу эстет, в его провинции люди аккуратно подбирают ингредиенты, поэтому он ставит низкие оценки рестикам, где плохо оформлены блюда, посещает только дорогие заведения с рыбными блюдами и очень критичен 
5. Безумец Макс из Питера, у которого совершенно атрофировался язык из-за всех кушаний Китая и исчезли все деньги, поэтому он больше не ест мясо и рыбу, а перешел на лапшичку с овощами без специй, максимально пресно и дешево