---
title: "guys"
author: "Alena Smirnova"
date: "25 05 2017"
output: html_document
---

```{r}
# s_t = read.csv("/students/dvchuprina/proect_kutezh/sh_trip_text.csv")
# p_text = read_csv("~/proect_kutezh/p_rest_trip.csv", 
# col_types = cols(file = col_number(), 
# review_stars = col_number())) 


trip_test <- read_csv("/students/dvchuprina/proect_kutezh/guys/trip_test.csv")
# trip_test = trip_test[!is.na(trip_test$tag),]
# trip_test$query_n = as.character(trip_test$query_n)
# link = as.data.frame(unique(trip_test$link))
# link$num = rownames(link)
# names(link) = c("link","num")
# 
# trip_test = left_join(trip_test, link, by = "link")

# write.csv(trip_test, "trip_t.csv", row.names = F)




num <-c (322,288,383,114,186,52,303,315,11,213,351,387,158,39,160,246,299,384,304,151,324,404,183, 1,10,199,2,60,61,63,68,69,71)
italian <- c(4,3,3,5,5,4,2,3,5,4,2,4,3,1,4,1,4,5,4,2,3,3,2,4,3,3,4,5,1,5,3,4,5)
russian <- c(5,5,5,3,5,5,5,3,5,5,4,5,5,4,1,5,2,5,3,3,4,3,2,3,4,3,5,5,2,5,5,4,5)
american <- c(1,5,4,4,5,3,5,4,4,4,5,4,5,4,2,5,2,4,5,2,5,4,4,4,5,4,4,5,3,5,5,4,5)
swedish <- c(5,1,5,5,5,5,2,4,3,4,1,2,1,2,4,3,1,4,3,1,4,3,1,5,3,3,2,5,1,5,2,2,1)
german <- c(4,3,3,5,4,3,3,2,4,5,3,3,5,3,1,4,3,4,4,3,4,3,2,4,5,2,3,5,3,5,5,4,5)


tab <- data.frame(num = num, Italian = italian, Russian = russian, American = american, Swedish = swedish, German = german, Spaniard = spanish)

write.csv(tab, "eu_guys.csv", row.names = F)
```



```{r}
shan = read.csv("/students/dvchuprina/proect_kutezh/guys/shan.csv")

shan$review_text = as.character(shan$review_text)
shan$file = as.character(shan$file)

y = select(shan,review_text, file)

func_paste <- function(x) paste(unique(x), collapse = ', ')
a20 = y %>%
    group_by(file) %>%
    summarise_each(funs(func_paste))
```


```{r}
#  для Кати теги
trip_test <- read_csv("/students/dvchuprina/proect_kutezh/guys/trip_test.csv")
# beijing_rests (query_n)
p_rest_trip <- read_csv("~/proect_kutezh/p_rest_trip.csv", 
    col_types = cols(file = col_number(), 
        review_date = col_number(), review_stars = col_number()))
# shanghai rests (file = query_n)
s_t = read.csv("/students/dvchuprina/proect_kutezh/sh_trip_text.csv")

new_tags = select(trip_test, link, query_n, city, num)
new_tags = unique(new_tags)

dudka_tag = select(new_tags, num)
dudka_tag = dudka_tag[c(1:244),]

dudka_tag$new_tag = c("")

```

